### ISSUE TITLE
bug: digital ocean failures with registry and automation api

### ISSUE THREAD

**Issue by qdzlug** [nginxinc/kic-reference-architectures#169]
**Describe the bug**
While testing the automation-api branch, the following errors are thrown on run:

```
  digitalocean:index:ContainerRegistry (shared-global-container-registry):
    error: could not validate provider configuration: 4 errors occurred:
        * Invalid or unknown key
        * Invalid or unknown key
        * Invalid or unknown key
        * Invalid or unknown key

Resources:
    + 1 created

Duration: 2s

ERROR:root:Error running Pulumi operation with provider [do] for stack [jaytest10]
Traceback (most recent call last):
  File "/home/jschmidt/scratch/kic-reference-architectures/pulumi/python/automation/main.py", line 482, in <module>
    main()
  File "/home/jschmidt/scratch/kic-reference-architectures/pulumi/python/automation/main.py", line 219, in main
    raise e
  File "/home/jschmidt/scratch/kic-reference-architectures/pulumi/python/automation/main.py", line 215, in main
    pulumi_cmd(provider=provider, env_config=env_config)
  File "/home/jschmidt/scratch/kic-reference-architectures/pulumi/python/automation/main.py", line 449, in up
    stack_up_result = stack.up(color=env_config.pulumi_color_settings(),
  File "/home/jschmidt/scratch/kic-reference-architectures/pulumi/python/venv/lib/python3.10/site-packages/pulumi/automation/_stack.py", line 284, in up
    up_result = self._run_pulumi_cmd_sync(args, on_output)
  File "/home/jschmidt/scratch/kic-reference-architectures/pulumi/python/venv/lib/python3.10/site-packages/pulumi/automation/_stack.py", line 663, in _run_pulumi_cmd_sync
    result = _run_pulumi_cmd(args, self.workspace.work_dir, envs, on_output)
  File "/home/jschmidt/scratch/kic-reference-architectures/pulumi/python/venv/lib/python3.10/site-packages/pulumi/automation/_cmd.py", line 78, in _run_pulumi_cmd
    raise create_command_error(result)
pulumi.automation.errors.CommandError:
 code: 255
 stdout: Updating (jaytest10)

View Live: https://app.pulumi.com/qdzlug/container-registry/jaytest10/updates/1


    pulumi:pulumi:Stack container-registry-jaytest10  Creating new global Digital Ocean container registry
 +  pulumi:pulumi:Stack container-registry-jaytest10 creating Creating new global Digital Ocean container registry
    digitalocean:index:ContainerRegistry shared-global-container-registry  error: could not validate provider configuration: 4 errors occurred:
 +  pulumi:pulumi:Stack container-registry-jaytest10 created 1 message
    digitalocean:index:ContainerRegistry shared-global-container-registry **failed** 1 error

Diagnostics:
  pulumi:pulumi:Stack (container-registry-jaytest10):
    Creating new global Digital Ocean container registry

  digitalocean:index:ContainerRegistry (shared-global-container-registry):
    error: could not validate provider configuration: 4 errors occurred:
        * Invalid or unknown key
        * Invalid or unknown key
        * Invalid or unknown key
        * Invalid or unknown key

Resources:
    + 1 created

Duration: 2s

 stderr:
```

**To Reproduce**
1. Checkout automation branch.
2. Add a config to the environment file (stack name)
3. Build w/ the do provider.

**Expected behavior**
Should...work.

**Your environment**
* AutomationAPI branch 24ee0c0993be09361e96695c0eeb0dd7bccc5926
* Linux / PopOS 22.04

**Additional context**
None.

**Comment by qdzlug** [comment]
Will be closed by #167 on merge.
